name: Display a bug -- external file

on:
  workflow_call:
    outputs:
      token:
        value: ${{ jobs.external-file-output.outputs.token }}
jobs:
  external-file-output:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.token }}
    steps:
      - name: Get token
        id: get-token
        run: echo "::set-output name=token::Outside"

