name: Display a bug -- external file

on: 
  workflow_call

jobs:
  external-file-output:
    id: external-file-output
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.token }}
    steps:
      - name: Get token
        id: get-token
        run: echo "::set-output name=token::Outside"

