name: Display a bug

on:
  push:
    branch: main

jobs: 
  in-file-output:
    runs-on: ubuntu-latest
    outputs: 
      token: ${{ steps.get-token.outputs.token }}
    steps:
      - name: Get Token
        id: get-token
        run: echo "::set-output name=token::This one is generated inside main script" 

  main:
    runs-on: ubuntu-latest
    needs: in-file-output
    steps:
      - name: main
        run: |  
          echo ${{ needs.in-file-output.outputs.token }}
