name: step 2

on:
  workflow_run:
    workflows:
      - "step 1"
    types:
      - completed

jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - name: branch
        run: echo "the branch"